import { useContext, useEffect, useMemo, useState } from "react";
import { PreferencesContext, useAppPreferences } from "./PreferencesContext";
import { AuthTextContext } from "./auth/AuthTextContext";
import { authTranslations } from "./auth/translations";

const uiTranslations = {
  en: {
    navStandards: "Standards", navHow: "How It Works", navAbout: "About", navDashboard: "Dashboard", navLogin: "Login", navRegister: "Get Started", logout: "Logout", home: "Home", helloThere: "Hello there", helloPrefix: "Hello,", browseStandards: "Browse Standards", viewCertifications: "View Certifications", notSpecified: "Not specified", detailsLoadError: "Standard details could not be loaded", standardsUnavailable: "Standards could not be loaded. Please try again.", isNumber: "IS Number", clearSearch: "Clear search", filterByCategory: "Filter by category", filterByStatus: "Filter by status", filterByCertification: "Filter by certification", quickCategory: "Quick category filters", heroEyebrow: "AI-POWERED PROCUREMENT INTELLIGENCE", heroTitleBefore: "Find the Right", heroTitleStandard: "Indian Standard", heroTitleAfter: "Before You Procure.", heroDescription: "Turn tender language into standards you can trust. ProcureIQ reads the material, application, and procurement context to surface relevant Indian Standards.", findStandards: "Find Standards", exploreStandards: "Explore Standards", prototypeStandards: "Prototype Standards", semanticMatching: "Semantic Matching", tenderAnalysis: "Tender Analysis",
    procurementIntelligence: "PROCUREMENT INTELLIGENCE", dashboardIntro: "Discover relevant Indian Standards from your procurement requirements.", liveMatching: "Live matching engine", findStandard: "Find the right standard", searchPlaceholder: "Describe your procurement requirement...", searchAria: "Describe your procurement requirement", searchButton: "Search Standards", example: "Example:", analyzing: "Analyzing...", uploadTender: "Upload Tender PDF", aiRecommendations: "AI RECOMMENDATIONS", recommendedStandards: "Recommended Standards", noMatches: "No matching standards found", tryAnother: "Try another search term or describe the requirement more clearly.", semanticMatch: "Semantic Match", quickActions: "QUICK ACTIONS", workflow: "Workflow", recentSearches: "RECENT SEARCHES", recent: "Recent", matches: "matches", sessionError: "Your session is no longer authorized. Please log in again.", validationError: "The search request failed validation. Please revise your query and try again.", serviceError: "The AI recommendation service is temporarily unavailable. Please try again shortly.", backendError: "The ProcureIQ backend cannot currently be reached. Please check your connection and try again.", genericError: "Recommendations could not be loaded. Please try again.",
    libraryTitle: "Indian Standards Library", libraryIntro: "Explore, search and understand relevant Indian Standards.", curated: "Curated Standards", categories: "Categories", acrossCorpus: "Across the full corpus", compliance: "Compliance", information: "Information", searchAllStandards: "Search by IS number, title, scope or keyword...", category: "Category", status: "Status", certification: "Certification", allCategories: "All categories", allStatuses: "All statuses", allCertifications: "All certifications", all: "All", resetFilters: "Reset filters", loadingStandards: "Loading standards...", unableStandards: "Standards could not be loaded", noStandards: "No standards found", adjustFilters: "Try a different search term or adjust your filters.", showing: "Showing", of: "of", total: "total", previous: "Previous", next: "Next", viewDetails: "View Details", edition: "Edition", notFound: "Standard not found", backStandards: "Back to Standards", overview: "STANDARD OVERVIEW", editionYear: "Edition Year", superseding: "Superseding IS", amendmentCount: "Amendment Count", latestAmendment: "Latest Amendment Note", verification: "Verification Status", certificationCompliance: "CERTIFICATION & COMPLIANCE", certificationStatus: "Certification Status", certificationType: "Certification Type", qcoReference: "QCO Reference", relatedStandards: "RELATED STANDARDS", exploreAll: "Explore all standards", procurementResearch: "Use this standard as part of your procurement research and validate the latest applicability against authoritative sources before making a decision."
  },
  hi: {
    navStandards: "मानक", navHow: "यह कैसे काम करता है", navAbout: "परिचय", navDashboard: "डैशबोर्ड", navLogin: "लॉग इन", navRegister: "शुरू करें", logout: "लॉग आउट", home: "होम", browseStandards: "मानक देखें", viewCertifications: "प्रमाणन देखें", notSpecified: "निर्दिष्ट नहीं", detailsLoadError: "मानक का विवरण लोड नहीं हो सका", standardsUnavailable: "मानक लोड नहीं हो सके। कृपया फिर से प्रयास करें।", isNumber: "IS संख्या", clearSearch: "खोज मिटाएँ", filterByCategory: "श्रेणी के अनुसार फ़िल्टर करें", filterByStatus: "स्थिति के अनुसार फ़िल्टर करें", filterByCertification: "प्रमाणन के अनुसार फ़िल्टर करें", quickCategory: "त्वरित श्रेणी फ़िल्टर", heroEyebrow: "एआई-संचालित खरीद बुद्धिमत्ता", heroTitleBefore: "सही", heroTitleStandard: "भारतीय मानक", heroTitleAfter: "खरीदने से पहले खोजें।", heroDescription: "निविदा की भाषा को भरोसेमंद मानकों से जोड़ें। ProcureIQ सामग्री, उपयोग और खरीद के संदर्भ को समझकर प्रासंगिक भारतीय मानक दिखाता है।", findStandards: "मानक खोजें", exploreStandards: "मानक देखें", prototypeStandards: "प्रोटोटाइप मानक", semanticMatching: "अर्थगत मिलान", tenderAnalysis: "निविदा विश्लेषण",
    procurementIntelligence: "खरीद बुद्धिमत्ता", dashboardIntro: "अपनी खरीद आवश्यकताओं के लिए प्रासंगिक भारतीय मानक खोजें।", liveMatching: "लाइव मिलान इंजन", findStandard: "सही मानक खोजें", searchPlaceholder: "अपनी खरीद आवश्यकता का वर्णन करें...", searchAria: "अपनी खरीद आवश्यकता का वर्णन करें", searchButton: "मानक खोजें", example: "??????:", analyzing: "विश्लेषण हो रहा है...", uploadTender: "टेंडर PDF अपलोड करें", aiRecommendations: "एआई सुझाव", recommendedStandards: "अनुशंसित मानक", noMatches: "कोई मेल खाने वाला मानक नहीं मिला", tryAnother: "कोई अन्य शब्द आज़माएँ या आवश्यकता को अधिक स्पष्ट रूप से बताएँ।", semanticMatch: "अर्थगत मिलान", quickActions: "त्वरित कार्रवाइयाँ", workflow: "कार्यप्रवाह", recentSearches: "हाल की खोजें", recent: "हाल की", matches: "मिलान", sessionError: "आपका सत्र अधिकृत नहीं है। कृपया फिर से लॉग इन करें।", validationError: "खोज अनुरोध की जाँच में त्रुटि हुई। कृपया अपनी क्वेरी बदलकर फिर प्रयास करें।", serviceError: "एआई सुझाव सेवा अभी उपलब्ध नहीं है। कृपया थोड़ी देर बाद प्रयास करें।", backendError: "ProcureIQ बैकएंड अभी उपलब्ध नहीं है। अपना कनेक्शन जाँचें और फिर प्रयास करें।", genericError: "सुझाव लोड नहीं हो सके। कृपया फिर से प्रयास करें।",
    libraryTitle: "भारतीय मानक पुस्तकालय", libraryIntro: "प्रासंगिक भारतीय मानकों को देखें, खोजें और समझें।", curated: "चयनित मानक", categories: "श्रेणियाँ", acrossCorpus: "पूरे संग्रह में", compliance: "अनुपालन", information: "जानकारी", searchAllStandards: "IS नंबर, शीर्षक, दायरा या कीवर्ड से खोजें...", category: "श्रेणी", status: "स्थिति", certification: "प्रमाणन", allCategories: "सभी श्रेणियाँ", allStatuses: "सभी स्थितियाँ", allCertifications: "सभी प्रमाणन", all: "सभी", resetFilters: "फ़िल्टर रीसेट करें", loadingStandards: "मानक लोड हो रहे हैं...", unableStandards: "मानक लोड नहीं हो सके", noStandards: "कोई मानक नहीं मिला", adjustFilters: "कोई अन्य शब्द आज़माएँ या फ़िल्टर बदलें।", showing: "दिखाए जा रहे", of: "में से", total: "कुल", previous: "पिछला", next: "अगला", viewDetails: "विवरण देखें", edition: "संस्करण", notFound: "मानक नहीं मिला", backStandards: "मानकों पर वापस जाएँ", overview: "मानक का सारांश", editionYear: "संस्करण वर्ष", superseding: "इसके स्थान पर मानक", amendmentCount: "संशोधन संख्या", latestAmendment: "नवीनतम संशोधन विवरण", verification: "सत्यापन स्थिति", certificationCompliance: "प्रमाणन और अनुपालन", certificationStatus: "प्रमाणन स्थिति", certificationType: "प्रमाणन प्रकार", qcoReference: "QCO संदर्भ", relatedStandards: "संबंधित मानक", exploreAll: "सभी मानक देखें", procurementResearch: "इस मानक का उपयोग खरीद अनुसंधान में करें और निर्णय से पहले आधिकारिक स्रोतों से इसकी वर्तमान प्रयोज्यता की पुष्टि करें।", backToStandards: "मानकों पर वापस जाएँ"
  },
  mr: {
    navStandards: "मानके", navHow: "हे कसे कार्य करते", navAbout: "माहिती", navDashboard: "डॅशबोर्ड", navLogin: "लॉग इन", navRegister: "सुरू करा", logout: "लॉग आउट", home: "मुख्यपृष्ठ", browseStandards: "मानके पाहा", viewCertifications: "प्रमाणने पहा", notSpecified: "नमूद केलेले नाही", detailsLoadError: "मानकाचा तपशील लोड करता आला नाही", standardsUnavailable: "मानके लोड करता आली नाहीत. कृपया पुन्हा प्रयत्न करा.", isNumber: "IS क्रमांक", clearSearch: "शोध साफ करा", filterByCategory: "वर्गानुसार फिल्टर करा", filterByStatus: "स्थितीनुसार फिल्टर करा", filterByCertification: "प्रमाणनानुसार फिल्टर करा", quickCategory: "जलद वर्ग फिल्टर", heroEyebrow: "एआय-आधारित खरेदी बुद्धिमत्ता", heroTitleBefore: "योग्य", heroTitleStandard: "भारतीय मानक", heroTitleAfter: "खरेदीपूर्वी शोधा.", heroDescription: "निविदेतील मजकूर विश्वासार्ह मानकांशी जोडा. ProcureIQ सामग्री, वापर आणि खरेदीचा संदर्भ समजून संबंधित भारतीय मानके दाखवते.", findStandards: "मानके शोधा", exploreStandards: "मानके पाहा", prototypeStandards: "प्रोटोटाइप मानके", semanticMatching: "अर्थाधारित जुळणी", tenderAnalysis: "निविदा विश्लेषण",
    procurementIntelligence: "खरेदी बुद्धिमत्ता", dashboardIntro: "तुमच्या खरेदीच्या गरजांसाठी संबंधित भारतीय मानके शोधा.", liveMatching: "थेट जुळणी प्रणाली", findStandard: "योग्य मानक शोधा", searchPlaceholder: "तुमच्या खरेदीच्या गरजेचे वर्णन करा...", searchAria: "तुमच्या खरेदीच्या गरजेचे वर्णन करा", searchButton: "मानके शोधा", example: "??????:", analyzing: "विश्लेषण सुरू आहे...", uploadTender: "निविदा PDF अपलोड करा", aiRecommendations: "एआय शिफारसी", recommendedStandards: "शिफारस केलेली मानके", noMatches: "जुळणारे मानक आढळले नाही", tryAnother: "दुसरा शोधशब्द वापरा किंवा गरजेचे अधिक स्पष्ट वर्णन करा.", semanticMatch: "अर्थाधारित जुळणी", quickActions: "जलद कृती", workflow: "कार्यप्रवाह", recentSearches: "अलीकडील शोध", recent: "अलीकडील", matches: "जुळण्या", sessionError: "तुमचे सत्र अधिकृत नाही. कृपया पुन्हा लॉग इन करा.", validationError: "शोध विनंतीची पडताळणी अयशस्वी झाली. कृपया क्वेरी बदलून पुन्हा प्रयत्न करा.", serviceError: "एआय शिफारस सेवा तात्पुरती उपलब्ध नाही. कृपया थोड्या वेळाने प्रयत्न करा.", backendError: "ProcureIQ बॅकएंड सध्या उपलब्ध नाही. तुमचे कनेक्शन तपासून पुन्हा प्रयत्न करा.", genericError: "शिफारसी लोड करता आल्या नाहीत. कृपया पुन्हा प्रयत्न करा.",
    libraryTitle: "भारतीय मानक ग्रंथालय", libraryIntro: "संबंधित भारतीय मानके पाहा, शोधा आणि समजून घ्या.", curated: "निवडक मानके", categories: "वर्ग", acrossCorpus: "संपूर्ण संग्रहात", compliance: "अनुपालन", information: "माहिती", searchAllStandards: "IS क्रमांक, शीर्षक, व्याप्ती किंवा कीवर्डने शोधा...", category: "वर्ग", status: "स्थिती", certification: "प्रमाणन", allCategories: "सर्व वर्ग", allStatuses: "सर्व स्थिती", allCertifications: "सर्व प्रमाणने", all: "सर्व", resetFilters: "फिल्टर रीसेट करा", loadingStandards: "मानके लोड होत आहेत...", unableStandards: "मानके लोड करता आली नाहीत", noStandards: "मानक आढळले नाही", adjustFilters: "दुसरा शोधशब्द वापरा किंवा फिल्टर बदला.", showing: "दाखवत आहे", of: "पैकी", total: "एकूण", previous: "मागील", next: "पुढील", viewDetails: "तपशील पहा", edition: "आवृत्ती", notFound: "मानक आढळले नाही", backStandards: "मानकांकडे परत", overview: "मानकाचा आढावा", editionYear: "आवृत्ती वर्ष", superseding: "याच्या जागी आलेले मानक", amendmentCount: "दुरुस्ती संख्या", latestAmendment: "नवीनतम दुरुस्तीची नोंद", verification: "पडताळणी स्थिती", certificationCompliance: "प्रमाणन आणि अनुपालन", certificationStatus: "प्रमाणन स्थिती", certificationType: "प्रमाणन प्रकार", qcoReference: "QCO संदर्भ", relatedStandards: "संबंधित मानके", exploreAll: "सर्व मानके पहा", procurementResearch: "या मानकाचा वापर खरेदी संशोधनासाठी करा आणि निर्णयापूर्वी अधिकृत स्रोतांकडून त्याची सद्य लागूता तपासा."
  }
};

const languages = ["en", "hi", "mr"];

const pageTranslations = {
  en: {
    howKicker: "HOW IT WORKS", howTitle: "From requirement to reliable procurement insight.", howIntro: "ProcureIQ uses semantic understanding, standards matching, and compliance context to make procurement decisions more confident and faster.", stepsFromQuery: "6 Steps", queryToDecision: "From query to decision", processFlow: "PROCESS FLOW", workflowTitle: "How the platform interprets a procurement requirement", stage: "STAGE",
    aboutKicker: "ABOUT PROCUREIQ", aboutTitle: "Making Indian Standards easier to discover.", aboutIntro: "ProcureIQ brings semantic AI and structured standards intelligence into the procurement workflow.", corePillars: "FOUR CORE PILLARS", pillarsTitle: "Standards discovery, made more intelligent.", pillarsIntro: "Purpose-built capabilities help move from everyday language to structured procurement insight.", semanticUnderstanding: "Semantic Understanding", semanticDescription: "Reads intent and context beyond exact keyword matches.", multilingualInput: "Multilingual Input", multilingualDescription: "Understands local-language phrasing and mixed-language queries.", standardsIntelligence: "Standards Intelligence", standardsDescription: "Connects procurement needs to relevant Indian Standards.", complianceAwareness: "Compliance Awareness", complianceDescription: "Surfaces certification and compliance context early.", productIdea: "THE PRODUCT IDEA", productIdeaTitle: "From a requirement to a better workflow.", productIdeaIntro: "Each step adds useful context, connecting the initial need to actionable standards intelligence.", technologyStack: "TECHNOLOGY STACK", technologyTitle: "Modern tools. One coherent product.", aboutCtaKicker: "DISCOVER WHAT APPLIES", aboutCtaTitle: "Find the standards behind better procurement.", aboutCtaButton: "Explore the Standards Library"
  },
  hi: {
    howKicker: "यह कैसे काम करता है", howTitle: "आवश्यकता से भरोसेमंद खरीद जानकारी तक।", howIntro: "ProcureIQ अर्थ, मानक मिलान और अनुपालन संदर्भ का उपयोग करके खरीद निर्णयों को अधिक भरोसेमंद और तेज़ बनाता है।", stepsFromQuery: "6 चरण", queryToDecision: "क्वेरी से निर्णय तक", processFlow: "प्रक्रिया प्रवाह", workflowTitle: "प्लेटफ़ॉर्म खरीद आवश्यकता को कैसे समझता है", stage: "चरण",
    aboutKicker: "PROCUREIQ के बारे में", aboutTitle: "भारतीय मानकों को खोजना आसान बनाएँ।", aboutIntro: "ProcureIQ खरीद प्रक्रिया में अर्थगत एआई और व्यवस्थित मानक जानकारी जोड़ता है।", corePillars: "चार मुख्य आधार", pillarsTitle: "मानक खोज को अधिक बुद्धिमान बनाएँ।", pillarsIntro: "विशेष सुविधाएँ रोज़मर्रा की भाषा को व्यवस्थित खरीद जानकारी में बदलती हैं।", semanticUnderstanding: "अर्थ की समझ", semanticDescription: "सटीक कीवर्ड से आगे जाकर आशय और संदर्भ समझता है।", multilingualInput: "बहुभाषी इनपुट", multilingualDescription: "स्थानीय भाषा और मिश्रित भाषा की क्वेरी समझता है।", standardsIntelligence: "मानक बुद्धिमत्ता", standardsDescription: "खरीद आवश्यकताओं को प्रासंगिक भारतीय मानकों से जोड़ता है।", complianceAwareness: "अनुपालन जानकारी", complianceDescription: "प्रमाणन और अनुपालन संदर्भ जल्दी सामने लाता है।", productIdea: "उत्पाद का विचार", productIdeaTitle: "आवश्यकता से बेहतर कार्यप्रवाह तक।", productIdeaIntro: "हर चरण उपयोगी संदर्भ जोड़कर शुरुआती आवश्यकता को मानक जानकारी से जोड़ता है।", technologyStack: "तकनीकी ढाँचा", technologyTitle: "आधुनिक साधन। एक सुसंगत उत्पाद।", aboutCtaKicker: "लागू मानक खोजें", aboutCtaTitle: "बेहतर खरीद के लिए आवश्यक मानक खोजें।", aboutCtaButton: "मानक पुस्तकालय देखें"
  },
  mr: {
    howKicker: "हे कसे कार्य करते", howTitle: "गरजेपासून विश्वासार्ह खरेदी माहितीकडे.", howIntro: "ProcureIQ अर्थसमज, मानक जुळणी आणि अनुपालन संदर्भ वापरून खरेदीचे निर्णय अधिक विश्वासार्ह आणि जलद करते.", stepsFromQuery: "6 टप्पे", queryToDecision: "क्वेरीपासून निर्णयापर्यंत", processFlow: "प्रक्रिया प्रवाह", workflowTitle: "प्लॅटफॉर्म खरेदीची गरज कशी समजतो", stage: "टप्पा",
    aboutKicker: "PROCUREIQ विषयी", aboutTitle: "भारतीय मानके शोधणे सोपे करा.", aboutIntro: "ProcureIQ खरेदी प्रक्रियेत अर्थाधारित एआय आणि संरचित मानक माहिती आणते.", corePillars: "चार मुख्य आधार", pillarsTitle: "मानकांचा शोध अधिक बुद्धिमान करा.", pillarsIntro: "विशेष क्षमता दैनंदिन भाषेला संरचित खरेदी माहितीत रूपांतरित करतात.", semanticUnderstanding: "अर्थसमज", semanticDescription: "अचूक कीवर्डच्या पलीकडील हेतू आणि संदर्भ समजते.", multilingualInput: "बहुभाषिक इनपुट", multilingualDescription: "स्थानिक भाषा आणि मिश्र भाषेतील क्वेरी समजते.", standardsIntelligence: "मानक बुद्धिमत्ता", standardsDescription: "खरेदीच्या गरजा संबंधित भारतीय मानकांशी जोडते.", complianceAwareness: "अनुपालन जागरूकता", complianceDescription: "प्रमाणन आणि अनुपालन संदर्भ आधीच दाखवते.", productIdea: "उत्पादनाची कल्पना", productIdeaTitle: "गरजेपासून चांगल्या कार्यप्रवाहापर्यंत.", productIdeaIntro: "प्रत्येक टप्पा उपयुक्त संदर्भ जोडून सुरुवातीची गरज कृतीयोग्य मानक माहितीत जोडतो.", technologyStack: "तंत्रज्ञान संच", technologyTitle: "आधुनिक साधने. एक सुसंगत उत्पादन.", aboutCtaKicker: "लागू मानके शोधा", aboutCtaTitle: "चांगल्या खरेदीसाठी आवश्यक मानके शोधा.", aboutCtaButton: "मानक ग्रंथालय पाहा"
  }
};

const contentTranslations = {
  en: {
    wfNeed: "Requirement", wfNeedText: "Start with the need described in a tender or procurement brief.", wfMeaning: "Semantic Understanding", wfMeaningText: "Interpret material, application, and context—not just keywords.", wfMatch: "AI Matching", wfMatchText: "Find Indian Standards that best fit the understood requirement.", wfVerify: "Verification", wfVerifyText: "Check relevant standard details and supporting relationships.", wfCertify: "Certification", wfCertifyText: "Surface certification and compliance context for review.", wfDecision: "Procurement", wfDecisionText: "Use the verified insight to make a more confident decision.",
    journeyNeed: "Procurement Requirement", journeyNeedText: "Tender or brief", journeyAI: "AI Understanding", journeyAIText: "Material, intent, context", journeyStandards: "Relevant Standards", journeyStandardsText: "Context-aware matches", journeyInfo: "Structured Intelligence", journeyInfoText: "Connected information", journeyWorkflow: "Better Procurement Workflow", journeyWorkflowText: "Clearer decisions"
  },
  hi: {
    wfNeed: "आवश्यकता", wfNeedText: "निविदा या खरीद विवरण में बताई गई आवश्यकता से शुरुआत करें।", wfMeaning: "अर्थ की समझ", wfMeaningText: "केवल कीवर्ड नहीं, सामग्री, उपयोग और संदर्भ समझें।", wfMatch: "एआई मिलान", wfMatchText: "समझी गई आवश्यकता के लिए उपयुक्त भारतीय मानक खोजें।", wfVerify: "सत्यापन", wfVerifyText: "मानक का विवरण और उससे जुड़े संबंध जाँचें।", wfCertify: "प्रमाणन", wfCertifyText: "समीक्षा के लिए प्रमाणन और अनुपालन संदर्भ दिखाएँ।", wfDecision: "खरीद", wfDecisionText: "अधिक भरोसेमंद निर्णय के लिए सत्यापित जानकारी का उपयोग करें।",
    journeyNeed: "खरीद आवश्यकता", journeyNeedText: "निविदा या विवरण", journeyAI: "एआई समझ", journeyAIText: "सामग्री, आशय, संदर्भ", journeyStandards: "प्रासंगिक मानक", journeyStandardsText: "संदर्भ के अनुसार मिलान", journeyInfo: "व्यवस्थित जानकारी", journeyInfoText: "जुड़ी हुई जानकारी", journeyWorkflow: "बेहतर खरीद प्रक्रिया", journeyWorkflowText: "अधिक स्पष्ट निर्णय"
  },
  mr: {
    wfNeed: "गरज", wfNeedText: "निविदा किंवा खरेदीच्या संक्षिप्त वर्णनातील गरजेपासून सुरुवात करा.", wfMeaning: "अर्थसमज", wfMeaningText: "फक्त कीवर्ड नव्हे, तर सामग्री, वापर आणि संदर्भ समजून घ्या.", wfMatch: "एआय जुळणी", wfMatchText: "समजलेल्या गरजेशी योग्य भारतीय मानके शोधा.", wfVerify: "पडताळणी", wfVerifyText: "मानकाचा तपशील आणि संबंधित दुवे तपासा.", wfCertify: "प्रमाणन", wfCertifyText: "पुनरावलोकनासाठी प्रमाणन आणि अनुपालन संदर्भ दाखवा.", wfDecision: "खरेदी", wfDecisionText: "अधिक विश्वासार्ह निर्णयासाठी पडताळलेली माहिती वापरा.",
    journeyNeed: "खरेदीची गरज", journeyNeedText: "निविदा किंवा संक्षिप्त माहिती", journeyAI: "एआय समज", journeyAIText: "सामग्री, हेतू, संदर्भ", journeyStandards: "संबंधित मानके", journeyStandardsText: "संदर्भानुसार जुळणी", journeyInfo: "संरचित माहिती", journeyInfoText: "जोडलेली माहिती", journeyWorkflow: "चांगली खरेदी प्रक्रिया", journeyWorkflowText: "अधिक स्पष्ट निर्णय"
  }
};

const adminTranslations = {
  en: { adminConsole: "ADMIN CONSOLE", adminDashboard: "ADMIN DASHBOARD", adminDashboardTitle: "Procurement Intelligence Control Center", adminName: "Admin", standardsManagement: "STANDARDS MANAGEMENT", manageStandards: "Manage Standards", addStandard: "Add Standard", prototypeForm: "Prototype add-standard form.", addDemoStandard: "Add Demo Standard", totalStandards: "Total Standards", activeStandards: "Active Standards", certificationRecords: "Certification Records", relationships: "Relationships", settings: "Settings", mainWebsite: "Main Website", actions: "Actions", standardTitleLabel: "Title", adminEmail: "Admin Email", adminPassword: "Password", secureAccess: "Secure access", adminIntro: "Manage standards intelligence and procurement data.", enterAdmin: "Enter Admin Console", userLogin: "User Login" },
  hi: { adminConsole: "व्यवस्थापक कंसोल", adminDashboard: "व्यवस्थापक डैशबोर्ड", adminDashboardTitle: "खरीद बुद्धिमत्ता नियंत्रण केंद्र", adminName: "व्यवस्थापक", standardsManagement: "मानक प्रबंधन", manageStandards: "मानक प्रबंधित करें", addStandard: "मानक जोड़ें", prototypeForm: "मानक जोड़ने का प्रारूप।", addDemoStandard: "डेमो मानक जोड़ें", totalStandards: "कुल मानक", activeStandards: "सक्रिय मानक", certificationRecords: "प्रमाणन रिकॉर्ड", relationships: "संबंध", settings: "सेटिंग्स", mainWebsite: "मुख्य वेबसाइट", actions: "कार्रवाई", standardTitleLabel: "शीर्षक", adminEmail: "व्यवस्थापक ईमेल", adminPassword: "पासवर्ड", secureAccess: "सुरक्षित प्रवेश", adminIntro: "मानक जानकारी और खरीद डेटा प्रबंधित करें।", enterAdmin: "व्यवस्थापक कंसोल खोलें", userLogin: "उपयोगकर्ता लॉगिन" },
  mr: { adminConsole: "प्रशासक कन्सोल", adminDashboard: "प्रशासक डॅशबोर्ड", adminDashboardTitle: "खरेदी बुद्धिमत्ता नियंत्रण केंद्र", adminName: "प्रशासक", standardsManagement: "मानक व्यवस्थापन", manageStandards: "मानके व्यवस्थापित करा", addStandard: "मानक जोडा", prototypeForm: "मानक जोडण्याचा नमुना फॉर्म.", addDemoStandard: "डेमो मानक जोडा", totalStandards: "एकूण मानके", activeStandards: "सक्रिय मानके", certificationRecords: "प्रमाणन नोंदी", relationships: "संबंध", settings: "सेटिंग्ज", mainWebsite: "मुख्य वेबसाइट", actions: "कृती", standardTitleLabel: "शीर्षक", adminEmail: "प्रशासक ईमेल", adminPassword: "पासवर्ड", secureAccess: "सुरक्षित प्रवेश", adminIntro: "मानक माहिती आणि खरेदी डेटा व्यवस्थापित करा.", enterAdmin: "प्रशासक कन्सोल उघडा", userLogin: "वापरकर्ता लॉगिन" }
};

function readPreference(key, fallback, accepted) {
  const value = localStorage.getItem(key);
  return accepted.includes(value) ? value : fallback;
}

export function AppPreferencesProvider({ children }) {
  const [theme, setTheme] = useState(() => readPreference("procureiq_theme", "light", ["light", "dark"]));
  const [language, setLanguage] = useState(() => readPreference("procureiq_language", "en", languages));

  useEffect(() => {
    document.documentElement.dataset.theme = theme;
    localStorage.setItem("procureiq_theme", theme);
  }, [theme]);

  useEffect(() => {
    document.documentElement.lang = language;
    localStorage.setItem("procureiq_language", language);
  }, [language]);

  const t = useMemo(() => (key) =>
    authTranslations[language]?.[key] ?? uiTranslations[language]?.[key] ?? pageTranslations[language]?.[key] ?? contentTranslations[language]?.[key] ?? adminTranslations[language]?.[key]
    ?? authTranslations.en?.[key] ?? uiTranslations.en?.[key] ?? pageTranslations.en?.[key] ?? contentTranslations.en?.[key] ?? adminTranslations.en?.[key] ?? key,
  [language]);

  return (
    <PreferencesContext.Provider value={{ theme, setTheme, language, setLanguage }}>
      <AuthTextContext.Provider value={t}>{children}</AuthTextContext.Provider>
    </PreferencesContext.Provider>
  );
}

export function PreferenceControls() {
  const { theme, setTheme, language, setLanguage } = useAppPreferences();
  const t = useContext(AuthTextContext);
  return (
    <div className="auth-header-controls">
      <button
        type="button"
        className="auth-theme-toggle"
        onClick={() => setTheme(theme === "light" ? "dark" : "light")}
        aria-label={t(theme === "light" ? "themeDark" : "themeLight")}
        title={t(theme === "light" ? "themeDark" : "themeLight")}
      >
        <span aria-hidden="true">{theme === "light" ? "◐" : "☼"}</span>
        <span className="auth-theme-label">{t(theme === "light" ? "darkMode" : "lightMode")}</span>
      </button>
      <label className="auth-language-control">
        <span className="visually-hidden">{t("language")}</span>
        <select value={language} onChange={(event) => setLanguage(event.target.value)} aria-label={t("language")}>
          <option value="en">English</option>
          <option value="hi">हिन्दी</option>
          <option value="mr">मराठी</option>
        </select>
      </label>
    </div>
  );
}
